//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Tests.TTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TTService.ITimeTrackerService")]
    public interface ITimeTrackerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeTrackerService/HelloFriends", ReplyAction="http://tempuri.org/ITimeTrackerService/HelloFriendsResponse")]
        string HelloFriends();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeTrackerService/HelloFriends", ReplyAction="http://tempuri.org/ITimeTrackerService/HelloFriendsResponse")]
        System.Threading.Tasks.Task<string> HelloFriendsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeTrackerServiceChannel : Service.Tests.TTService.ITimeTrackerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeTrackerServiceClient : System.ServiceModel.ClientBase<Service.Tests.TTService.ITimeTrackerService>, Service.Tests.TTService.ITimeTrackerService {
        
        public TimeTrackerServiceClient() {
        }
        
        public TimeTrackerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeTrackerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeTrackerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeTrackerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloFriends() {
            return base.Channel.HelloFriends();
        }
        
        public System.Threading.Tasks.Task<string> HelloFriendsAsync() {
            return base.Channel.HelloFriendsAsync();
        }
    }
}
