//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hours
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string ActivityID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<decimal> Hours1 { get; set; }
    }
}
